application: mazawww
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  static_files: static/index.html
  upload: static/index.html
  mime_type: text/html

- url: /javascript
  static_dir: javascript
  mime_type: text/javascript
  
- url: /css
  static_dir: css
  mime_type: text/css
  
- url: /fonts
  static_dir: fonts

- url: /js
  static_dir: js
  mime_type: text/javascript
  
- url: /img
  static_dir: img
  
- url: /bg
  static_dir: bg

- url: /images
  static_dir: images
  
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  mime_type: image/x-icon

- url: /science/demo
  static_files: static/ncert-science-electromagnetism.pdf
  upload: static/ncert-science-electromagnetism.pdf
  mime_type: application/pdf
  
- url: /(.*)
  static_files: static/\1
  upload: static/(.*)
  mime_type: text/html
