application: mazawww
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: index.html
  upload: index.html
  mime_type: text/html

- url: /pocketdoctor
  static_files: pocketdoctor/index.html
  upload: pocketdoctor/index.html
  mime_type: text/html

- url: /physicsstudio
  static_files: physicsstudio/index.html
  upload: physicsstudio/index.html
  mime_type: text/html

- url: /ios.html
  static_files: distribution/ios.html
  upload: distribution/ios.html
  mime_type: text/html

- url: /tos.html
  static_files: tos.html
  upload: tos.html
  mime_type: text/html

- url: /launchapi.html
  static_files: launchapi.html
  upload: launchapi.html
  mime_type: text/html

- url: /content.html
  static_files: content.html
  upload: content.html
  mime_type: text/html

- url: /privacy.html
  static_files: privacy.html
  upload: privacy.html
  mime_type: text/html

- url: /termsofuse.html
  static_files: termsofuse.html
  upload: termsofuse.html
  mime_type: text/html

- url: /press/press5Jul2015.html
  static_files: press/PressRelease-5Jul2015.html
  upload: press/PressRelease-5Jul2015.html
  mime_type: text/html

- url: /press/press15Aug2015.html
  static_files: press/PressRelease-15Aug2015.html
  upload: press/PressRelease-15Aug2015.html
  mime_type: text/html

- url: /press/press15Jun2017.html
  static_files: press/PressRelease-15Jun2017.html
  upload: press/PressRelease-15Jun2017.html
  mime_type: text/html

- url: /distribution/scienceengineios-1.0.plist
  static_files: distribution/scienceengineios-1.0.plist
  upload: distribution/scienceengineios-1.0.plist
  mime_type: application/xml

- url: /distribution/scienceenginerobovm.ipa
  static_files: distribution/scienceenginerobovm.ipa
  upload: distribution/scienceenginerobovm.ipa
  mime_type: application/octet-stream

- url: /info
  script: main.application

- url: /javascript
  static_dir: javascript
  mime_type: text/javascript
  
- url: /css
  static_dir: css
  mime_type: text/css
  
- url: /fonts
  static_dir: fonts

- url: /js
  static_dir: js
  mime_type: text/javascript
  
- url: /img
  static_dir: img
 
- url: /pocketdoctor/img
  static_dir: pocketdoctor/img
 
- url: /physicsstudio/img
  static_dir: physicsstudio/img
 
- url: /distribution
  static_dir: distribution
  
- url: /bg
  static_dir: bg

- url: /images
  static_dir: images
  
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  mime_type: image/x-icon

- url: /science/demo
  static_files: static/ncert-science-electromagnetism.pdf
  upload: static/ncert-science-electromagnetism.pdf
  mime_type: application/pdf
  
- url: /scienceengine
  script: main.application

- url: /science/(.*)
  script: main.application

- url: /(.*)
  static_files: static/\1
  upload: static/(.*)
  mime_type: text/html
